### ISSUE TITLE
세미나 언제 하시나요?

### ISSUE THREAD

**Issue by Jungmo** [jafffy/repoForGitSeminar#1]
주말인가요??

**Comment by jafffy** [comment]
다음 주 수요일에 의대에서 합니다 ㅋㅋ
이번엔 내부 세미나라서 다른 분들이 듣긴 힘드실 것 같고, 추후에 해당 material 갖고 다른 분들께도 세미나 할 생각은 있습니다.

**Comment by Jungmo** [comment]
네 ㅠㅠ 자료 잘 보겠습니다
